# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations

# doc: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
changelog:

  exclude:

    labels:
      - 'Release process'
      - 'ci:no-build'
  
  # order matters since this works like a filter, a PR will show up only once.
  # try to keep similar categories together since this is also the rendering order.
  categories:

    - title: 'Gradle'
      labels:
        - 'Gradle'

    - title: 'Maven'
      labels:
        - 'Maven'

    - title: 'Ant'
      labels:
        - 'Ant'

    - title: 'Java'
      labels:
        - 'Java'
        - 'JavaDoc'

    - title: 'JavaFX'
      labels:
        - 'JavaFX'

    - title: 'Groovy'
      labels:
        - 'Groovy'

    - title: 'PHP'
      labels:
        - 'PHP'

    - title: 'C/C++'
      labels:
        - 'C/C++'

    - title: 'Enterprise'
      labels:
        - 'enterprise'
        - 'Java EE/Jakarta EE'
        - 'Micronaut'
        - 'Payara'

    - title: 'Web'
      labels:
        - 'JavaScript'
        - 'TypeScript'
        - 'HTML'
        - 'CSS'
        - 'CSL'

    - title: 'Versioning'
      labels:
        - 'git'
        - 'subversion'
        - 'mercurial'

    - title: 'Editor'
      labels:
        - 'Editor'
        - 'ANTLR'
        - 'Docker'

    - title: 'UI Changes'
      labels:
        - 'UI'
        - 'Look and Feel'

    - title: 'Platform'
      labels:
        - 'Platform'

    - title: 'Language Server Protocol'
      labels:
        - 'LSP'

    - title: 'VSCode Extension'
      labels:
        - 'VSCode Extension'

    - title: 'Maintenance'
      labels:
        - 'Code cleanup'
        - 'Upgrade Library'
        - 'dependencies'
        - 'CI'

    - title: Other Changes
      labels:
        - "*"
