#!/bin/sh -x

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
set -e

dirname=`dirname "$0"`

. "$dirname"/env.sh

"$dirname"/unpack200.sh "$2/$NETBEANS_INSTALL_DIR" "$2/$NETBEANS_INSTALL_DIR/Contents/Resources/NetBeans"

"$dirname"/add_gf.sh "$2/$NETBEANS_INSTALL_DIR" "/Applications/NetBeans/glassfish-v2ur1"

"$dirname"/add_tc.sh "$2/$NETBEANS_INSTALL_DIR" "/Applications/NetBeans/apache-tomcat-6.0.16"

jdk_home_1_5=/System/Library/Frameworks/JavaVM.framework/Versions/1.5/Home
cd "$2/$NETBEANS_INSTALL_DIR"
cd Contents/Resources/NetBeans*/etc
if [ -f netbeans.conf ]
then
  echo netbeans.conf found: `pwd`/netbeans.conf
  if [ -d $jdk_home_1_5 ]
  then
    echo 1.5 JDK home exists: $jdk_home_1_5
    cp netbeans.conf netbeans.conf_orig_jdk_home
    cat netbeans.conf_orig_jdk_home  | sed -e 's|.*netbeans_jdkhome.*|netbeans_jdkhome='$jdk_home_1_5'|' > netbeans.conf
  else
    echo No 1.5 JDK home: $jdk_home_1_5
  fi
else
  echo No netbeans.conf in: `pwd`
fi

#fix for 114656
cd "$2/$NETBEANS_INSTALL_DIR"
cd Contents/Resources/NetBeans*/nb
mkdir var
touch var/license_accepted

cd "$2/$NETBEANS_INSTALL_DIR"
chmod -R g+w ./

if [ -d "/Library/Receipts/NetBeans.pkg" ] ; then
    rm -rf "/Library/Receipts/NetBeans.pkg"
fi
