#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# XXX consider using lastStableBuild
BUILD=`wget http://deadlock.nbextras.org/hudson/job/trunk/lastSuccessfulBuild/buildNumber -O -`

TESTDIST="http://deadlock.netbeans.org/job/test-compilation/lastSuccessfulBuild/artifact/nbbuild/build/testdist.zip"
PLATFORM="http://deadlock.netbeans.org/job/trunk/lastSuccessfulBuild/artifact/nbbuild/dist/zip/netbeans-hudson-trunk-$BUILD-platform.zip"

[ -f `basename $TESTDIST` ] || wget $TESTDIST
[ -f `basename $PLATFORM` ] || wget $PLATFORM


rm -rf testdist
mkdir testdist
unzip testdist.zip -d testdist

rm -rf netbeans
mkdir netbeans
unzip netbeans*platform*.zip -d netbeans
mkdir netbeans/etc
echo >netbeans/etc/netbeans.conf

#-ant -f testdist/build.xml unit -Dnetbeans.dest.dir=`pwd`/netbeans
ant -f testdist/unit/unit-all-unit.xml runtests -Dnetbeans.dest.dir=`pwd`/netbeans $*





