/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.cnd.simpleunit.wizard;

import java.util.List;
import javax.swing.JPanel;
import org.netbeans.modules.cnd.api.model.CsmDeclaration;
import org.netbeans.modules.cnd.modelutil.ui.ElementNode.Description;
import org.openide.util.NbBundle;

public final class GenerateTestChooseElementsVisualPanel extends JPanel {
    private final FunctionSelectorPanel elementSelector;

    /** Creates new form GenerateTestChooseElementsVisualPanel */
    public GenerateTestChooseElementsVisualPanel() {
        initComponents();
        elementSelector = (FunctionSelectorPanel) funSelector;
//        elementSelector = new FunctionSelectorPanel(false);
//        java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
//        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
//        gridBagConstraints.weightx = 1.0;
//        gridBagConstraints.weighty = 1.0;
//        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
//        add(elementSelector, gridBagConstraints);
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(GenerateTestChooseElementsVisualPanel.class, "GenerateTestChooseElementsWizardPanelName");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        funSelector = new FunctionSelectorPanel(false);

        jLabel1.setLabelFor(funSelector);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(GenerateTestChooseElementsVisualPanel.class, "GenerateTestChooseElementsVisualPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
            .addComponent(funSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(funSelector, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void setRootElement(Description description) {
        elementSelector.initFromElement(description, false);
        elementSelector.doInitialExpansion(1);
    }

    List<CsmDeclaration> getSelectedElements() {
        return elementSelector.getSelectedElements();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel funSelector;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    void showLoadingNode() {
        elementSelector.showLoadingNode();
    }
}
