/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.java.disco;

import eu.hansolo.jdktools.TermOfSupport;
import io.foojay.api.discoclient.pkg.Distribution;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import org.checkerframework.checker.guieffect.qual.UIEffect;
import org.checkerframework.checker.nullness.qual.MonotonicNonNull;
import org.checkerframework.checker.nullness.qual.NonNull;

public class QuickPanel extends javax.swing.JPanel {

    private final DefaultComboBoxModel<Distribution> distrosModel = new DefaultComboBoxModel<>();

    public QuickPanel() {
        initComponents();
        distributionComboBox.setRenderer(new DistributionListCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JLabel versionLabel = new javax.swing.JLabel();
        versions = new javax.swing.JSlider();
        autoInstallJDK = new javax.swing.JRadioButton();
        manualJDK = new javax.swing.JRadioButton();
        javax.swing.JLabel distributionLabel = new javax.swing.JLabel();
        distributionComboBox = new javax.swing.JComboBox<>();

        org.openide.awt.Mnemonics.setLocalizedText(versionLabel, org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.versionLabel.text")); // NOI18N

        versions.setMaximum(20);
        versions.setMinimum(8);
        versions.setPaintLabels(true);
        versions.setPaintTicks(true);
        versions.setSnapToTicks(true);
        versions.setValue(15);
        versions.setInverted(true);

        buttonGroup1.add(autoInstallJDK);
        autoInstallJDK.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(autoInstallJDK, org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.autoInstallJDK.text")); // NOI18N
        autoInstallJDK.setToolTipText(org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.autoInstallJDK.toolTipText")); // NOI18N

        buttonGroup1.add(manualJDK);
        org.openide.awt.Mnemonics.setLocalizedText(manualJDK, org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.manualJDK.text")); // NOI18N
        manualJDK.setToolTipText(org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.manualJDK.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(distributionLabel, org.openide.util.NbBundle.getMessage(QuickPanel.class, "QuickPanel.distributionLabel.text")); // NOI18N

        distributionComboBox.setModel(createDistrosModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoInstallJDK, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(manualJDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(distributionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(distributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(versionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versions, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel)
                    .addComponent(versions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distributionLabel)
                    .addComponent(distributionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(autoInstallJDK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manualJDK)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton autoInstallJDK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<Distribution> distributionComboBox;
    private javax.swing.JRadioButton manualJDK;
    private javax.swing.JSlider versions;
    // End of variables declaration//GEN-END:variables

    private ComboBoxModel<Distribution> createDistrosModel() {
        return distrosModel;
    }

    public void updateDistributions(List<Distribution> distributions, Distribution defaultDist) {
        distrosModel.removeAllElements();
        distributions.stream()
                .sorted((o1, o2) -> o1.getUiString().compareTo(o2.getUiString()))
                .forEachOrdered(distrosModel::addElement);
        distributionComboBox.setSelectedItem(defaultDist);
    }

    //The `versions` slider holds *the index* in versionsJDKs and
    //this model holds the actual JDKs and the mapping between
    static class VersionsModel {

        private final List<Integer> versionJDKs;
        private final Map<Integer, TermOfSupport> lts;

        private VersionsModel(List<Integer> jdks, Map<Integer, TermOfSupport> lts) {
            this.versionJDKs = new ArrayList<>(jdks);
            //quick panel shows only maintained JDKs
            versionJDKs.removeIf(v -> !lts.containsKey(v));
            versionJDKs.removeIf(v -> v < 8);
            this.lts = lts;
        }

        public int getMinimum() {
            return 0;
        }

        public int getMaximum() {
            return versionJDKs.size() - 1;
        }

        public int getDefaultValue() {
            return versionJDKs.indexOf(LTSes.latest(lts));
        }

        @UIEffect
        @NonNull
        public Hashtable<Integer, JLabel> createLabels() {
            Hashtable<Integer, JLabel> labels = new Hashtable<>();
            for (Integer v : versionJDKs) {
                boolean isLTS = lts.get(v) == TermOfSupport.LTS;
                String name = LTSes.text(v, lts.get(v));
                JLabel label = new JLabel(name);
                if (isLTS) {
                    //these decorations do nothing on macOS...
                    Font font = label.getFont();
                    label.setFont(font.deriveFont(font.getStyle() | Font.BOLD));
                    label.setToolTipText("Long Term Support");
                }
                labels.put(versionJDKs.indexOf(v), label);
            }
            return labels;
        }

        private int getJDK(int index) {
            return versionJDKs.get(index);
        }

    }

    @MonotonicNonNull
    private VersionsModel versionsModel;

    void setVersions(List<Integer> jdks, Map<Integer, TermOfSupport> lts) {
        versionsModel = new VersionsModel(jdks, lts);
        versions.setMaximum(versionsModel.getMaximum());
        versions.setMinimum(versionsModel.getMinimum());
        versions.setLabelTable(versionsModel.createLabels());
        versions.setValue(versionsModel.getDefaultValue());
    }

    @UIEffect
    @NonNull
    QuickSelection getSelectedPackage() {
        return new QuickSelection((Distribution) distributionComboBox.getSelectedItem(), versionsModel.getJDK(versions.getValue()), autoInstallJDK.isSelected());
    }

    static class QuickSelection {

        final int version;
        final boolean zip;
        final Distribution distribution;

        public QuickSelection(Distribution dist, int version, boolean zip) {
            this.distribution = dist;
            this.version = version;
            this.zip = zip;
        }
    }
}
