/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/*
 * FixCodeAssistancePanel.java
 *
 * Created on Jan 21, 2011, 3:13:22 PM
 */
package org.netbeans.modules.cnd.toolchain.ui.compilerset;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.netbeans.modules.cnd.api.toolchain.CompilerSetManager;
import org.netbeans.modules.cnd.api.toolchain.Tool;
import org.netbeans.modules.cnd.toolchain.support.ToolchainUtilities;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.awt.NotificationDisplayer;
import org.openide.util.ImageUtilities;
import org.openide.util.NbBundle;

/**
 *
 */
public class FixCodeAssistancePanel extends javax.swing.JPanel {

    /** Creates new form FixCodeAssistancePanel */
    private FixCodeAssistancePanel(Map<Tool, List<List<String>>> needReset) {
        initComponents();
        StringBuilder buf = new StringBuilder();
        for(Map.Entry<Tool, List<List<String>>> entry : needReset.entrySet()) {
            Tool key = entry.getKey();
            if (buf.length() > 0) {
                buf.append('\n'); // NOI18N
            }
            buf.append(key.getCompilerSet()).append(" ").append(key.getDisplayName()); // NOI18N
        }
        textArea.setText(NbBundle.getMessage(FixCodeAssistancePanel.class, "FixCodeAssistancePanel.message", buf.toString()));
    }

    public static void showNotification(final Map<Tool, List<List<String>>> needReset, final CompilerSetManager csm) {
        final String title = NbBundle.getMessage(FixCodeAssistancePanel.class, "FixCodeAssistancePanel.title.text"); // NOI18N
        ActionListener onClickAction = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                JButton btnOk = new JButton( NbBundle.getMessage(FixCodeAssistancePanel.class, "FixCodeAssistancePanel.action.OK")); // NOI18N
                JButton btnCancel = new JButton( NbBundle.getMessage(FixCodeAssistancePanel.class, "FixCodeAssistancePanel.action.CANCEL")); // NOI18N
                FixCodeAssistancePanel panel = new FixCodeAssistancePanel(needReset);
                DialogDescriptor descriptor = new DialogDescriptor(panel, title,
                        true, new Object[]{btnOk,btnCancel}, DialogDescriptor.CLOSED_OPTION,
                        DialogDescriptor.DEFAULT_ALIGN, null, null);
                if (DialogDisplayer.getDefault().notify(descriptor) == btnOk) {
                    ToolchainUtilities.fixCSM(needReset, csm);
                }
            }
        };
        ImageIcon icon = ImageUtilities.loadImageIcon("org/netbeans/modules/cnd/toolchain/compilerset/exclamation.gif", false); // NOI18N
        NotificationDisplayer.getDefault().notify(title, icon,
                NbBundle.getMessage(FixCodeAssistancePanel.class, "FixCodeAssistancePanel.action.text"), // NOI18N
                onClickAction, NotificationDisplayer.Priority.HIGH, NotificationDisplayer.Category.WARNING); // NOI18N
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 0, 6));
        setPreferredSize(new java.awt.Dimension(350, 100));
        setLayout(new java.awt.BorderLayout());

        textArea.setColumns(20);
        textArea.setEditable(false);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
