#!/bin/sh
#set -x
real_tool=echo
if [ -n "${__CND_BUILD_LOG__}" ]; then
    OS=`uname`; 
    if [ $OS = Darwin -o $OS = FreeBSD ]; then 
        __CND_TEMP_FILE__=`mktemp -t nbwrapper`
    else
        __CND_TEMP_FILE__=`mktemp`
    fi
    echo "called: ${real_tool}" > ${__CND_TEMP_FILE__}
    echo "\t`pwd`" >> ${__CND_TEMP_FILE__}
    echo "\t${real_tool}" >> ${__CND_TEMP_FILE__}
    for opt in "$@"; do
        echo "\t${opt}" >> ${__CND_TEMP_FILE__}
    done
    echo >> ${__CND_TEMP_FILE__}
    cat ${__CND_TEMP_FILE__} >> ${__CND_BUILD_LOG__}
    rm ${__CND_TEMP_FILE__}
fi
PATH=`dirname "${real_tool}"`:${PATH}
export PATH
exec "${real_tool}" "$@"
