#!/bin/sh -x

#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright 1997-2010 Oracle and/or its affiliates. All rights reserved.
#
# Oracle and Java are registered trademarks of Oracle and/or its affiliates.
# Other names may be trademarks of their respective owners.
#
# The contents of this file are subject to the terms of either the GNU General Public
# License Version 2 only ("GPL") or the Common Development and Distribution
# License("CDDL") (collectively, the "License"). You may not use this file except in
# compliance with the License. You can obtain a copy of the License at
# http://www.netbeans.org/cddl-gplv2.html or nbbuild/licenses/CDDL-GPL-2-CP. See the
# License for the specific language governing permissions and limitations under the
# License.  When distributing the software, include this License Header Notice in
# each file and include the License file at nbbuild/licenses/CDDL-GPL-2-CP.  Oracle
# designates this particular file as subject to the "Classpath" exception as provided
# by Oracle in the GPL Version 2 section of the License file that accompanied this code.
# If applicable, add the following below the License Header, with the fields enclosed
# by brackets [] replaced by your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
# 
# Contributor(s):
# 
# The Original Software is NetBeans. The Initial Developer of the Original Software
# is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun Microsystems, Inc. All
# Rights Reserved.
# 
# If you wish your version of this file to be governed by only the CDDL or only the
# GPL Version 2, indicate your decision by adding "[Contributor] elects to include
# this software in this distribution under the [CDDL or GPL Version 2] license." If
# you do not indicate a single choice of license, a recipient has the option to
# distribute your version of this file under either the CDDL, the GPL Version 2 or
# to extend the choice of license to its licensees as provided above. However, if you
# add GPL Version 2 code and therefore, elected the GPL Version 2 license, then the
# option applies only if the new code is made subject to such option by the copyright
# holder.
# 

set -e

dirname=`dirname "$0"`

. "$dirname"/env.sh

"$dirname"/unpack200.sh "$2/$NETBEANS_INSTALL_DIR" "$2/$NETBEANS_INSTALL_DIR/Contents/Resources/NetBeans"

"$dirname"/add_gf.sh "$2/$NETBEANS_INSTALL_DIR" "/Applications/NetBeans/glassfish-v2ur1"

"$dirname"/add_tc.sh "$2/$NETBEANS_INSTALL_DIR" "/Applications/NetBeans/apache-tomcat-6.0.16"

jdk_home_1_5=/System/Library/Frameworks/JavaVM.framework/Versions/1.5/Home
cd "$2/$NETBEANS_INSTALL_DIR"
cd Contents/Resources/NetBeans*/etc
if [ -f netbeans.conf ]
then
  echo netbeans.conf found: `pwd`/netbeans.conf
  if [ -d $jdk_home_1_5 ]
  then
    echo 1.5 JDK home exists: $jdk_home_1_5
    cp netbeans.conf netbeans.conf_orig_jdk_home
    cat netbeans.conf_orig_jdk_home  | sed -e 's|.*netbeans_jdkhome.*|netbeans_jdkhome='$jdk_home_1_5'|' > netbeans.conf
  else
    echo No 1.5 JDK home: $jdk_home_1_5
  fi
else
  echo No netbeans.conf in: `pwd`
fi

#fix for 114656
cd "$2/$NETBEANS_INSTALL_DIR"
cd Contents/Resources/NetBeans*/nb
mkdir var
touch var/license_accepted

cd "$2/$NETBEANS_INSTALL_DIR"
chmod -R g+w ./

if [ -d "/Library/Receipts/NetBeans.pkg" ] ; then
    rm -rf "/Library/Receipts/NetBeans.pkg"
fi
