#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

LIB_DIR=`dirname $0`/../lib
LIB_DIR=`readlink -f $LIB_DIR`
CLASSPATH_SOURCE="@CLASSPATH@"
CLASSPATH=""
for f in `echo $CLASSPATH_SOURCE | tr ':' '\n'`; do
    FILE=`find $LIB_DIR -name "$f"`;
    if [ -e "$FILE" ]; then
        CLASSPATH="$CLASSPATH:$FILE";
    fi;
done

java --add-exports jdk.javadoc/com.sun.tools.javadoc.main=ALL-UNNAMED -classpath "$CLASSPATH" org.netbeans.modules.java.lsp.server.Server
