<?xml version="1.0" encoding="UTF-8"?>
<definitions name="messageMultiDocumentation" 
    targetNamespace="http://j2ee.netbeans.org/wsdl/messageMultiDocumentation"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
    xmlns:tns="http://j2ee.netbeans.org/wsdl/messageMultiDocumentation" 
    xmlns:plink="http://schemas.xmlsoap.org/ws/2004/03/partner-link/">
    <types/>
    <message name="goodBasicWSDLOperationRequest">
        <documentation/>
        <documentation/>
        <part name="part1" type="xsd:string"></part>
    </message>
    <message name="goodBasicWSDLOperationReply">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="goodBasicWSDLPortType">
        <operation name="goodBasicWSDLOperation">
            <input name="input1" message="tns:goodBasicWSDLOperationRequest"/>
            <output name="output1" message="tns:goodBasicWSDLOperationReply"/>
        </operation>
    </portType>
    <binding name="goodBasicWSDLBinding" type="tns:goodBasicWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="goodBasicWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/goodBasicWSDL"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/goodBasicWSDL"/>
            </output>
        </operation>
    </binding>
    <service name="goodBasicWSDLService">
        <port name="goodBasicWSDLPort" binding="tns:goodBasicWSDLBinding">
            <soap:address location="http://localhost:18181/goodBasicWSDLService/goodBasicWSDLPort"/>
        </port>
    </service>
    <plink:partnerLinkType name="goodBasicWSDLPartner">
        <!-- partnerLinkType are automatically generated when a new portType is added. partnerLinkType are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plink:role name="goodBasicWSDLPortTypeRole" portType="tns:goodBasicWSDLPortType"/>
    </plink:partnerLinkType>
</definitions>
