<?xml version="1.0" encoding="utf-8" ?>
<definitions targetNamespace="http://enterprise.netbeans.org/bpel/wsdl/inventory/bp1"
             name="InventoryService"
             xmlns:tns="http://enterprise.netbeans.org/bpel/wsdl/inventory/bp1"
             xmlns:inv="http://enterprise.netbeans.org/bpel/xsd/inventory"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:plink="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:po="http://enterprise.netbeans.org/bpel/xsd/purchase"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <types>
        <xsd:schema targetNamespace="http://enterprise.netbeans.org/bpel/wsdl/inventory/bp1">
            <xsd:import schemaLocation="inventory.xsd" namespace="http://enterprise.netbeans.org/bpel/xsd/inventory"/>
            <xsd:import schemaLocation="purchaseOrder.xsd" namespace="http://enterprise.netbeans.org/bpel/xsd/purchase"/>
        </xsd:schema>
    </types>
    <message name="InventoryMessage">
        <part name="inventoryPart"
              element="inv:inventory"></part>
    </message>
    <message name="inventoryFault">
        <part name="faultInfo"
              type="xsd:string"></part>
    </message>
    <message name="POMessage">
        <part name="purchaseOrder"
              element="po:purchaseOrder"></part>
    </message>
    <portType name="inventoryPortType">
        <operation name="inventoryService">
            <input name="purchaseOrder"
                   message="tns:POMessage"></input>
            <output name="inventoryStatus"
                    message="tns:InventoryMessage"></output>
            <fault name="inventoryFaultType"
                   message="tns:inventoryFault"></fault>
        </operation>
    </portType>
    <binding name="inventoryBinding"
             type="tns:inventoryPortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="inventoryService">
            <input name="purchaseOrder">
                <soap:body parts="purchaseOrder"
                           use="literal"/>
            </input>
            <output name="inventoryStatus">
                <soap:body parts="inventoryPart"
                           use="literal"/>
            </output>
            <fault name="inventoryFaultType">
                <soap:fault name="faultInfo"
                            use="literal"/>
            </fault>
        </operation>
    </binding>
    <service name="inventoryService">
        <port name="inventoryServicePort"
              binding="tns:inventoryBinding">
            <soap:address location="http://localhost:12100/wsdl/inventory/ServiceLocation/bp1"/>
        </port>
    </service>
    
    <plink:partnerLinkType name="inventoryRequestingLT">
        <plink:role name="inventoryService"
                    portType="tns:inventoryPortType"></plink:role>
    </plink:partnerLinkType>
</definitions>
