/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.cnd.makeproject.ui;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.netbeans.modules.cnd.makeproject.api.TempEnv;
import org.netbeans.modules.nativeexecution.api.ExecutionEnvironment;
import org.openide.util.NbBundle;

/**
 *
 */
public class ResolveEnvVarPanel extends javax.swing.JPanel {
    private final EnvProjectProblemsProvider.UnsetEnvVar unset;

    /**
     * Creates new form ResolveEnvVarPanel
     */
    public ResolveEnvVarPanel(EnvProjectProblemsProvider.UnsetEnvVar unset) {
        initComponents();
        jTextPane1.setBackground(getBackground());
        this.unset = unset;
        int iy = 2;
        GridBagConstraints gridBagConstraints;
        for(final String var : unset.getUndefinedEnvVars()) {
            JLabel varLabel = new JLabel(var);
            gridBagConstraints = new GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = iy;
            gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
            gridBagConstraints.insets = new Insets(0, 6, 0, 6);
            add(varLabel, gridBagConstraints);
            
            ExecutionEnvironment env = unset.getExecutionEnvironment();
            String defValue = TempEnv.getInstance(env).getTemporaryEnv(var);
            if (defValue != null) {
                unset.editValue(var, defValue);
            }
            if (env.isRemote()) {
                jTextPane1.setText(NbBundle.getMessage(ResolveEnvVarPanel.class, "env_var_fix.solution.remote.text")); // NOI18N
            } else {
                jTextPane1.setText(NbBundle.getMessage(ResolveEnvVarPanel.class, "env_var_fix.solution.local.text")); // NOI18N
            }
            
            JTextField edit = new JTextField(defValue);
            gridBagConstraints = new GridBagConstraints();
            gridBagConstraints.gridx = 1;
            gridBagConstraints.gridy = iy++;
            gridBagConstraints.fill=GridBagConstraints.HORIZONTAL;
            gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
            gridBagConstraints.insets = new Insets(0, 6, 0, 6);
            add(edit, gridBagConstraints);
            edit.getDocument().addDocumentListener(new DocumentListenerImpl(var, edit));
        }
        JPanel filler = new JPanel();
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = iy++;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill=GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1;
        gridBagConstraints.weighty = 1;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(0, 0, 0, 0);
        add(filler, gridBagConstraints);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jTextPane1.setEditable(false);
        jTextPane1.setText(org.openide.util.NbBundle.getMessage(ResolveEnvVarPanel.class, "env_var_fix.solution.local.text")); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        add(jScrollPane1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ResolveEnvVarPanel.class, "env_var_fix.label.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    private class DocumentListenerImpl implements DocumentListener {

        private final String var;
        private final JTextField field;

        public DocumentListenerImpl(String var, JTextField field) {
            this.var = var;
            this.field = field;
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            unset.editValue(var, field.getText());
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            unset.editValue(var, field.getText());
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            unset.editValue(var, field.getText());
        }
    }
}
