<?xml version="1.0" encoding="UTF-8"?>
<definitions name="goodOWOperation" targetNamespace="http://j2ee.netbeans.org/wsdl/goodOWOperation"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/goodOWOperation" xmlns:plink="http://schemas.xmlsoap.org/ws/2004/03/partner-link/">
    <types/>
    <message name="goodOWOperationOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <portType name="goodOWOperationPortType">
        <operation name="goodOWOperationOperation">
            <input name="input1" message="tns:goodOWOperationOperationRequest">
                <documentation>Description of the input message.</documentation>
            </input>
            <fault name="shouldNotBeDefinied" message="tns:goodOWOperationOperationRequest" />
        </operation>
    </portType>
</definitions>
