#
# Sample TOML document
#

environment = "production"

[application]
name = "hello_world"
message = "TOML Says:\nHello World!"
short-description = """
This application says
Hello World!
"""
long-description = '''
This is an example TOML document.
'''

[dates]
odt1 = 1979-05-27T07:32:00Z
odt2 = 1979-05-27T00:32:00-07:00
odt3 = 1979-05-27T00:32:00.999999-07:00
odt4 = 1979-05-27 07:32:00Z
ldt1 = 1979-05-27T07:32:00
ldt2 = 1979-05-27T00:32:00.999999
ld1 = 1979-05-27
lt1 = 07:32:00
lt2 = 00:32:00.999999

[release]
version = '1.1'
revision = 42
snapshot = false

[[dependencies]]
package = 'foo'
version = '1.0.0'

[[dependencies]]
package = 'bar'
version = '1.2.3'

