#!/bin/sh
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


#set -x
real_tool=echo
if [ -n "${__CND_BUILD_LOG__}" ]; then
    OS=`uname`; 
    if [ $OS = Darwin -o $OS = FreeBSD ]; then 
        __CND_TEMP_FILE__=`mktemp -t nbwrapper`
    else
        __CND_TEMP_FILE__=`mktemp`
    fi
    echo "called: ${real_tool}" > ${__CND_TEMP_FILE__}
    echo "\t`pwd`" >> ${__CND_TEMP_FILE__}
    echo "\t${real_tool}" >> ${__CND_TEMP_FILE__}
    for opt in "$@"; do
        echo "\t${opt}" >> ${__CND_TEMP_FILE__}
    done
    echo >> ${__CND_TEMP_FILE__}
    cat ${__CND_TEMP_FILE__} >> ${__CND_BUILD_LOG__}
    rm ${__CND_TEMP_FILE__}
fi
PATH=`dirname "${real_tool}"`:${PATH}
export PATH
exec "${real_tool}" "$@"
