<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="wzdl4"
targetNamespace="http://localhost/BpelModule1/wzdl4"
xmlns:tns="http://localhost/BpelModule1/wzdl4"
xmlns:ns="http://schemas.xmlsoap.org/wsdl/soap/">
    <message name="message_0">
        <part name="part_0" type="xsd:boolean"/>
    </message>
    <portType name="portType_0">
        <operation name="operation_0">
            <input name="input1" message="tns:message_0"/>
            <output name="output1" message="tns:message_0"/>
        </operation>
    </portType>
</definitions>
