<?xml version="1.0" encoding="UTF-8"?>
<definitions name="newWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/newWSDL"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/newWSDL" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="newWSDLOperationRequest">
        <part name="part1" type="xsd:string"/>
        <part name="part2" type="xsd:string"/>
        <part name="part3" type="xsd:string"/>
    </message>
    <message name="reply1">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="ItineraryFault">
        <part name="faultMessage" element="tns:itineraryFault"/>
    </message>  
    <portType name="newWSDLPortType">
        <operation name="newWSDLOperation">
            <input name="input1" message="tns:newWSDLOperationRequest"/>
            <output name="output1" message="tns:newWSDLOperationReply"/>
        </operation>
    </portType>
    <binding name="newWSDLBinding" type="tns:newWSDLPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="newWSDLOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/newWSDL"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/newWSDL"/>
            </output>
        </operation>
    </binding>
    <service name="newWSDLService">
        <port name="newWSDLPort" binding="tns:newWSDLBinding">
            <soap:address location="http://localhost:18181/newWSDLService/newWSDLPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="newWSDL1">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="newWSDLPortTypeRole" portType="tns:newWSDLPortType"/>
    </plnk:partnerLinkType>
</definitions>
