<?php
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

namespace TodoList;

?>
<h1>Welcome!</h1>

<p class="p">Welcome to the NetBeans PHP IDE sample - <b>TODO List application</b>.</p>
<ul class="p">
    This sample does not use any PHP framework, it will show you possibilities how to:
    <li>prevent public access to your scripts</li>
    <li>config your application</li>
    <li>access your database data</li>
    <li>change your database data (with redirect-after-post pattern)</li>
    <li>validate your data</li>
    <li>split scripts and templates</li>
    <li>handle expected and unexpected exceptions</li>
</ul>
<p class="p">Detailed information can be found in the <i>readme.html</i> file (in project directory).</p>
<p class="p"><b>This sample is not intended to be used on a production server without any changes.</b></p>
