name: nb-javac
on: [push]
#  push:
#    branches: [ master ]
jobs:
  linux:
    name: "NetBeans on nb-javac"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: 8
      - name: Download External Binaries
        run: ant download-all-extbins
      - name: Build NetBeans with nb-javac
        run: ant build -Dnbjavac.class.path=java/libs.javacapi/external/*.jar
      - name: Setup Xvfb
        run: |
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Test with Commit Validation
        run: ant commit-validation -Dnbjavac.class.path=java/libs.javacapi/external/*.jar
