#!/bin/sh

# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright 2014 Oracle and/or its affiliates. All rights reserved.
#
# Oracle and Java are registered trademarks of Oracle and/or its affiliates.
# Other names may be trademarks of their respective owners.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common
# Development and Distribution License("CDDL") (collectively, the
# "License"). You may not use this file except in compliance with the
# License. You can obtain a copy of the License at
# http://www.netbeans.org/cddl-gplv2.html
# or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
# specific language governing permissions and limitations under the
# License.  When distributing the software, include this License Header
# Notice in each file and include the License file at
# nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
# particular file as subject to the "Classpath" exception as provided
# by Oracle in the GPL Version 2 section of the License file that
# accompanied this code. If applicable, add the following below the
# License Header, with the fields enclosed by brackets [] replaced by
# your own identifying information:
# "Portions Copyrighted [year] [name of copyright owner]"
#
# If you wish your version of this file to be governed by only the CDDL
# or only the GPL Version 2, indicate your decision by adding
# "[Contributor] elects to include this software in this distribution
# under the [CDDL or GPL Version 2] license." If you do not indicate a
# single choice of license, a recipient has the option to distribute
# your version of this file under either the CDDL, the GPL Version 2 or
# to extend the choice of license to its licensees as provided above.
# However, if you add GPL Version 2 code and therefore, elected the GPL
# Version 2 license, then the option applies only if the new code is
# made subject to such option by the copyright holder.
#
# Contributor(s):
#
# Portions Copyrighted 2014 Sun Microsystems, Inc.

set -e

dirname=`dirname "$0"`

jdk_home=`"$dirname"/get_current_jdk.sh`

. "$dirname"/env.sh

"$dirname"/add_gf.sh "$NETBEANS_INSTALL_DIR" "$GLASSFISH_INSTALL_DIR"

"$dirname"/add_javadb.sh "$NETBEANS_INSTALL_DIR" "$GLASSFISH_INSTALL_DIR/javadb"

"$dirname"/add_tc.sh "$NETBEANS_INSTALL_DIR" "$TOMCAT_INSTALL_DIR"

if [ -f "$dirname"/set_jdk_home.sh ]; then
    "$dirname"/set_jdk_home.sh "$NETBEANS_INSTALL_DIR" "$DEFAULT_JDK_HOME"
fi

"$dirname"/populate_caches.sh "$NETBEANS_INSTALL_DIR"
exit_code=$?
echo Result of populate_caches.sh : $exit_code

#fix for 114656
cd "$NETBEANS_INSTALL_DIR"
cd Contents/Resources/NetBeans*/${NB_CLUSTER_DIR}
mkdir -p var
touch var/license_accepted

#fix for 151681
"$dirname"/perm.sh "$NETBEANS_INSTALL_DIR"

#Fix for 151681
#Go to the /Application/NetBeans folder to change its permissions and ownership
chmod g+w "$NETBEANS_INSTALL_DIR"/..
chown root:wheel "$NETBEANS_INSTALL_DIR"/..
